# Generated by Django 4.2.2 on 2023-07-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('author', models.CharField(default='Неизвестный', max_length=50, verbose_name='Автор')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='todo', to='todo.status', verbose_name='Статус')),
                ('types', models.ManyToManyField(blank=True, related_name='todo', to='todo.type', verbose_name='Типы')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'todo',
            },
        ),
    ]
