# Generated by Django 4.2.2 on 2023-07-26 13:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230726_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_url_path, verbose_name='Аватар'),
        ),
    ]
