# Generated by Django 4.2.2 on 2023-07-26 14:03

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_url_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'], 'Корректные форматы файла ("jpg", "jpeg")'), accounts.models.validate_image_size], verbose_name='Аватар'),
        ),
    ]
