# Generated by Django 4.2.2 on 2023-07-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_slug',
            field=models.SlugField(null=True, verbose_name='Слаг'),
        ),
    ]
