# Generated by Django 4.2.2 on 2023-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20230705_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title_slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
