# Generated by Django 4.2.2 on 2023-07-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='удалено или нет'),
        ),
    ]
